table EquiposIntegrantesVENTAS
	lineageTag: ea32dae6-62d9-4baa-a2c7-075428e38662

	column Equipo
		dataType: string
		lineageTag: 92925df7-07f1-440c-9b7d-ed1bf6d40baf
		summarizeBy: none
		sourceColumn: Equipo

		annotation SummarizationSetBy = Automatic

	column Integrante
		dataType: string
		lineageTag: 7e015132-ee17-4a75-9550-6ec8d36e1964
		summarizeBy: none
		sourceColumn: Integrante

		annotation SummarizationSetBy = Automatic

	column IntegranteKey
		dataType: string
		lineageTag: aaea355f-92ed-4819-906f-1e8dfe05c5b9
		summarizeBy: none
		sourceColumn: IntegranteKey

		annotation SummarizationSetBy = Automatic

	partition EquiposIntegrantesVENTAS = m
		mode: import
		source =
				let
				    NormalizarNombre = (valor as any) as text => 				        let 				            Limpio = try Text.Trim(Text.Clean(Text.From(valor))) otherwise "", 				            Mayusculas = Text.Upper(Limpio), 				            SinDiacriticos = List.Accumulate({{"Á", "A"}, {"É", "E"}, {"Í", "I"}, {"Ó", "O"}, {"Ú", "U"}, {"Ü", "U"}}, Mayusculas, (estado, par) => Text.Replace(estado, par{0}, par{1})) 				        in 				            SinDiacriticos,
				    Source = Excel.Workbook(File.Contents("C:\Users\Usuario\DC\ACCDocs\GCPEASA\GCP_TRANSFORMACIÓN_DIGITAL\Project Files\01_IMPLEMENTACIÓN_BIM\0112_SQDCM\Equipos e integrantes - VENTAS.xlsx"), null, true),
				    IntegrantesSheet = Source{[Item="Integrantes", Kind="Sheet"]}[Data],
				    PromotedHeaders = Table.PromoteHeaders(IntegrantesSheet, [PromoteAllScalars=true]),
				    Selected = Table.SelectColumns(PromotedHeaders, {"Equipo", "Integrante"}),
				    AsText = Table.TransformColumns(Selected, {{"Equipo", each try Text.Trim(Text.Clean(Text.From(_))) otherwise null, type nullable text}, {"Integrante", each try Text.Trim(Text.Clean(Text.From(_))) otherwise null, type nullable text}}),
				    ValidRows = Table.SelectRows(AsText, each [Equipo] <> null and [Equipo] <> "" and [Integrante] <> null and [Integrante] <> ""),
				    WithKey = Table.AddColumn(ValidRows, "IntegranteKey", each NormalizarNombre([Integrante]), type text),
				    Output = Table.Distinct(WithKey, {"IntegranteKey"})
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

